title: Jordi Corbalan Vilaplana
description: Data Scientist & Data Analyst Portfolio.
author: Jordi Corbalan
email: corbalanjor@gmail.com
theme: jekyll-theme-minimal # Used as a fallback, but we prevent default styles by using our own CSS
plugins:
  - jekyll-seo-tag
